spring:
  security:
    user:
      name: admin
      password: 1234
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/patient_db
    username: patient_hub
    password: Pass_24
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  envers:
    #default_schema: public
    use_revision_entity_with_native_id: true
    audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
    audit_strategy_validity_store_revend_timestamp: true
logging:
  level:
    root: info
    com:
      example:
        demo:
          Patient:
            Service: trace


